apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pds.fullname" . }}
  labels:
    {{- include "pds.labels" . | nindent 4 }}
data:
  PDS_HOSTNAME: {{ .Values.pds.hostname }}
  {{- if not .Values.pds.postgresUrl }}
  PDS_DB_SQLITE_LOCATION: {{ .Values.pds.sqliteLocation }}
  {{- else }}
  PDS_DB_POSTGRES_URL: {{ .Values.pds.postgresUrl }}
  {{- end }}
  {{- if not .Values.pds.s3 }}
  PDS_BLOBSTORE_DISK_LOCATION: {{ .Values.pds.blobStorePath }}
  {{- end }}
  PDS_DID_PLC_URL: {{ .Values.pds.didPlcUrl }}
  PDS_BSKY_APP_VIEW_ENDPOINT: {{ .Values.pds.appViewEndpoint }}
  PDS_BSKY_APP_VIEW_DID: {{ .Values.pds.appViewDid }}
  PDS_CRAWLERS: {{ .Values.pds.crawlers }}
